# Generated by Django 5.0.4 on 2024-04-30 05:46

import localflavor.pk.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_1', models.CharField(max_length=100)),
                ('address_2', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(max_length=64)),
                ('state', localflavor.pk.models.PKStateField(max_length=5)),
                ('zip_code', localflavor.pk.models.PKPostCodeField(max_length=5)),
            ],
        ),
    ]
