# Generated by Django 5.0.4 on 2024-05-03 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_listing_color_alter_listing_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='box',
            field=models.CharField(choices=[('with-box', 'With Box'), ('without-box', 'Without Box')], default=None, max_length=24),
        ),
        migrations.AddField(
            model_name='listing',
            name='charger',
            field=models.CharField(choices=[('with-original-charger', 'With Original Charger'), ('without-original-charger', 'Without Original Charger')], default=None, max_length=24),
        ),
        migrations.AddField(
            model_name='listing',
            name='warranty',
            field=models.CharField(choices=[('warranty', 'Warranty'), ('no-warranty', 'No Warranty')], default=None, max_length=24),
        ),
    ]
