# Generated by Django 5.0.4 on 2024-05-04 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_listing_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='price',
        ),
    ]
